### PR TITLE
[README] Add #support_othercogs as a way to get support

### PR DESCRIPTION
**Pull request by OofChair**
Seeing as you're an approved cog creator now, I added the #support_othercogs channel as a way to get support.

😃👍🏼

### CODE REVIEW

**Comment by OofChair** [comment]
Also I'm not sure how links work in .rst files so couldn't link the cog support server 🤷🏼‍♂️

**Review by kreusada — CHANGES_REQUESTED** [review]
We can add links like this:

```rst
`click me <https://link>`_
```

Additionally, whilst you're there, would be nice to see an additional note regarding that this repo has been vetted by the QA team, otherwise looks good

**Comment by OofChair** [comment]
Should be good, tell me if I placed the QA note wrong

**Comment by kreusada** [comment]
All set, thanks for contributing! 🎉

**Pull request merged**
