### PR TITLE
[README] Add docs link to README

### PR DESCRIPTION
**Pull request by OofChair**
Did this on my phone, sorry if it’s bad :P

### CODE REVIEW

**Review by Just-Jojo — COMMENTED** [review]
LGTM

**Review by kreusada — CHANGES_REQUESTED** [review]
Looks good, but please resolve these merge conflicts so that this can be merged. Also, it might be better if it said "my docs" instead of "the docs".

**Comment by OofChair** [comment]
Merge conflicts are all good now, and I changed to "my docs."

**Review by kreusada — APPROVED** [review]
Thanks! 🎉

**Pull request merged**
